### ISSUE TITLE
Feature Request: "Created By" column

### ISSUE THREAD

**Issue by popbee** [Mimeo/VSTSExtension-ActivePullRequests#11]
We often identify pull requests by the person that created it. 

How easy would it be to add a "Created by" column?

**Comment by nshenoy** [comment]
Actually, this shouldn't be that difficult. According to the [docs](https://www.visualstudio.com/en-us/docs/integrate/api/git/pull-requests/pull-requests#get-a-list-of-pull-requests-in-the-repository), the response object has a `createdBy` property that has the display name and I guess the account alias. Would it be preferable to display that as something like `Nithin Shenoy <nshenoy@something.com>` or just display name or just the account alias?

**Comment by nshenoy** [comment]
And thanks for installing the extension and providing feedback! Much appreciated.

**Comment by popbee** [comment]
Good question, the minimal is the user name (displayName).  But probably the best would be similar to what is seen elsewhere in the product (with the user icon avatar and a tooltip containing the uniqueName at minimum).  (the email is the uniqueName which sometimes shows as "[domain]\name" instead of an email).

[avatar] Leonard Nimoy 
with tooltip: "lnimoy@ncc-1701.us"

Looking at the VSTS, the simplest I saw was in the Team Member list popup from the main project page (a grid cell):

```
<div class="grid-cell identity-cell" title="${uniqueName}" style="width: 200px;">
  <img class="identity-picture" src="${imageUrl}" alt="Image of ${uniqueName}">
  <span class="identity-name">${displayName}</span>
</div>
```

**Comment by nshenoy** [comment]
@popbee Check out the latest changes to the extension and let me know if this works for you. This is an initial implementation that wasn't able to use your snippet, unfortunately as the UI was extremely wonky. The docs mention that Grids don't allow for variable height rows yet, so I may have to play around do doing some custom UI shenanigans in the future to see if this can be achieved. 

Feel free to play around and open a PR if you can figure it out before I get around to it.

**Comment by popbee** [comment]
Hey! just tried it and it works nicely!  

Missing would be the "title" (for the tooltip) with the uniqueName. If you cannot put it on the grid cell "div", you can put it on the "span" I believe. Also I see the "font" of the name is not the same as the rest of the line. Other than that, it's amazing.

Do you really need variable height rows? Why not fixed?

If I want to play with the code (to eventually do a PR), would you know how I can "test" it out? How do people do this anyways?

Thanks again for your efforts! Appreciated.

**Comment by nshenoy** [comment]
I tried to make the font for the uniqueName a little smaller, but you're right in that it looks funny. I can fix that. And good idea with the tooltip!

I think I used "variable height" incorrectly in my original comment. What I meant to say was that I'm not sure how to adjust the height of a grid row; there's only properties for sizing the column width in the grid UI control and nothing for a row's height. I'll dig in some more though.

Testing is a bit of a pain to be honest. I don't exactly know how people test this stuff locally before deploying. I've been sort of doing #yolo development for this extension and hoping I don't break folks. :( I think one way to test this would be to change the manifest so that it's not public, and then publish to your own VSTS organization and try it out there. If things work well, then open a PR. You'd probably need to also change the IDs in the manifest. I can look into this more to see how others approach this cuz I honestly don't know.

Thanks!
